name: Deploy Cloud Run App

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'src/**'
      - 'pyproject.toml'
      - 'setup.py'
      - 'uv.lock'
      - '.github/workflows/deploy-cloud-run.yml'
      - 'app/Dockerfile'
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Override the image tag (defaults to commit SHA)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      CLOUD_RUN_SERVICE: ${{ vars.CLOUD_RUN_SERVICE }}
      CLOUD_RUN_REGION: ${{ vars.CLOUD_RUN_REGION }}
      ARTIFACT_REGISTRY_REPO: ${{ vars.ARTIFACT_REGISTRY_REPO }}
      ARTIFACT_REGISTRY_LOCATION: ${{ vars.ARTIFACT_REGISTRY_LOCATION }}
      IMAGE_NAME: kg-gen-app
      IMAGE_TAG: ${{ github.event.inputs.image_tag || github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure configuration is set
        run: |
          missing=0
          for var in GCP_PROJECT_ID CLOUD_RUN_SERVICE CLOUD_RUN_REGION ARTIFACT_REGISTRY_REPO; do
            if [ -z "${!var}" ]; then
              echo "::error::Set $var as a repository secret or variable before running this workflow."
              missing=1
            fi
          done
          if [ "$missing" -ne 0 ]; then
            exit 1
          fi
        shell: bash

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          chmod +x scripts/deploy_cloud_run.sh
          ./scripts/deploy_cloud_run.sh
        shell: bash
